### ISSUE TITLE
Consider adding hierarchy to labels

### ISSUE THREAD

**Issue by smihael** [ReconCycle/context_action_framework#1]
Currently, we have labels such as `hca_front `and `hca_back` (see https://github.com/ReconCycle/context_action_framework/blob/994624bc639e2e290ac925626f99e7dca04c9ed7/src/context_action_framework/types.py#L30C22-L30C22). For further processing, it would be beneficial if class hierarchy would be added. We could consider concepts from OOP, e.g. that HCAFront inherits from HCA. 

In the same fashion, distinguishing between different types (makes) of different electronic devices of the same family could be addressed (e.g. Hekatron can inherit from `smoke_detector`).

**Comment by sebastian-ruiz** [comment]
Done.
